"""Build Markdown and notebooks from the annotated Day*.py teaching sources."""
from pathlib import Path
import argparse
import json
import re
from course_guidance import navigation, theory_outputs

ROOT = Path(__file__).resolve().parents[1]


def render(path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("# %% [markdown]"):
        return {}
    cells = []
    for match in re.finditer(r"^# %%( \[markdown\])?\n(.*?)(?=^# %%|\Z)", text, re.M | re.S):
        kind = "markdown" if match[1] else "code"
        source = match[2].rstrip() + "\n"
        if kind == "markdown":
            source = "\n".join(line[2:] if line.startswith("# ") else line.removeprefix("#") for line in source.splitlines()) + "\n"
        cell = {"cell_type": kind, "metadata": {}, "source": source.splitlines(keepends=True)}
        if kind == "code":
            cell.update(execution_count=None, outputs=[])
        cells.append(cell)
    # Preserve the public Day 11 spelling and add source/notebook navigation.
    stem = path.stem.replace("Day 11_k-NN", "Day 11_K-NN")
    links = (f"[Python 源文件]({path.name.replace(' ', '%20')}) · "
             f"[Notebook]({stem.replace(' ', '%20')}.ipynb) · "
             "[完整课程目录](../docs/curriculum.md)\n")
    day = int(re.search(r"Day (\d+)", path.stem)[1])
    links += "\n" + navigation(day, path)
    cells.insert(1, {"cell_type": "markdown", "metadata": {}, "source": [links]})
    nb = {"cells": cells, "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python"}}, "nbformat": 4, "nbformat_minor": 4}
    notice = "<!-- Generated by tools/sync_lessons.py; edit the matching .py source. -->\n\n"
    md = notice + "\n".join("".join(c["source"]) if c["cell_type"] == "markdown" else "```python\n" + "".join(c["source"]) + "```\n" for c in cells)
    return {path.with_name(stem + ".md"): md, path.with_name(stem + ".ipynb"): json.dumps(nb, ensure_ascii=False, indent=1) + "\n"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = []
    for path in sorted((ROOT / "Code").glob("Day*.py")):
        for target, content in render(path).items():
            if not target.exists() or target.read_text(encoding="utf-8") != content:
                changed.append(str(target.relative_to(ROOT)))
                if not args.check:
                    target.write_text(content, encoding="utf-8")
    for target, content in theory_outputs().items():
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            changed.append(str(target.relative_to(ROOT)))
            if not args.check:
                target.write_text(content, encoding="utf-8")
    if args.check and changed:
        raise SystemExit("Out-of-sync lessons:\n" + "\n".join(changed))
    print(f"{'Checked' if args.check else 'Updated'} lessons; {len(changed)} files {'differ' if args.check else 'written'}.")


if __name__ == "__main__":
    main()
